# Foi utilizada a Action actions/upload-artifact, disponível no GitHub Marketplace, para armazenar os relatórios gerados pelos testes automatizados do Playwright.
#A solução facilita a análise dos resultados da execução, permitindo que a equipe faça download das evidências dos testes, identifique falhas e acompanhe a qualidade da aplicação diretamente pelo GitHub Actions.

name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Browsers do Playwright
        run: yarn playwright install --with-deps

      - name: Executando testes e2e
        run: yarn run e2e

      - name: Verificando arquivos gerados
        if: always()
        run: |
          pwd
          ls -la
          find . -type d -name "playwright-report"
          find . -type f -name "results.xml"

      - name: Upload dos relatórios
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-playwright
          path: |
            playwright-report/**
            results.xml
          retention-days: 7
